name: Scrape YouTube - @bogdanhxc

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  scrape_youtube_music:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      USER_ID: ${{ secrets.USER_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      YT_API_KEY: ${{ secrets.YT_API_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scrape_youtube_music.py
        run: |
          python scrape_youtube_music.py \
            --url "https://www.youtube.com/@bogdanhxc" \
            --full False \
            --model_name "openai/gpt-oss-120b" \
            --temperature 0.7
